"""Contract tests against the fixtures shared with the frontend.

``common_fixtures/<scenario>/`` is the meeting point between the two sides of
the wire protocol. Each side generates what it produces in production and
verifies what it consumes:

  * ``sse.txt`` — one POST /chat worth of stream. Generated here (live engine,
    scripted model); consumed by the frontend contract tests.
  * ``ui_messages.json`` — the session history as ``GET /sessions/{id}``
    serves it. Generated here; the frontend asserts its live-consumed state
    matches it (live/reload parity) and seeds resume tests from it.
  * ``approval_request.json`` — the POST body the browser sends after the
    user answers the approvals. Generated by the *frontend* test (the real
    ``Chat`` produces it); consumed here through the real session resume.

Regenerate with ``UPDATE_FIXTURES=1 uv run pytest tests/test_contract.py``
followed by ``UPDATE_FIXTURES=1 pnpm test`` in ``frontend/``.

Comparisons are exact except for two normalizations: generated ids
(``msg_*``/``part_*``) are canonicalized in encounter order, and preliminary
subagent progress lines are dropped — concurrent child pumps make their
interleaving genuinely unspecified, and their content is covered by
``ui_messages.json``.
"""

from __future__ import annotations

import asyncio
import json
import os
import pathlib
import re
from typing import Any

import ai
import ai.types.messages as messages_
import ai.ui.ai_sdk as ai_sdk
import httpx
import pytest
from conftest import MockProvider, assert_message_invariants, text_msg
from harness import (
    InProcessWorld,
    start_session,
    wait_for_lifecycle,
)

from agent import proto, session
from app import chat, server, sessions

FIXTURES_DIR = pathlib.Path(__file__).resolve().parents[2] / "common_fixtures"
UPDATE = bool(os.environ.get("UPDATE_FIXTURES"))

_VOLATILE_ID = re.compile(r"^(msg|part|turn|run)_[0-9a-f]+$")


def _canon(value: Any, mapping: dict[str, str] | None = None) -> Any:
    """Replace generated ids with stable placeholders, in encounter order."""
    if mapping is None:
        mapping = {}
    if isinstance(value, str) and _VOLATILE_ID.match(value):
        if value not in mapping:
            mapping[value] = f"id-{len(mapping)}"
        return mapping[value]
    if isinstance(value, dict):
        return {key: _canon(item, mapping) for key, item in value.items()}
    if isinstance(value, list):
        return [_canon(item, mapping) for item in value]
    return value


def _sse_projection(lines: list[str]) -> list[Any]:
    """The deterministic part of an SSE capture.

    Drops preliminary subagent progress (concurrent pumps, unspecified
    interleaving) and canonicalizes ids; everything else — event order,
    types, deltas, approval ids — must match exactly.
    """
    mapping: dict[str, str] = {}
    events = []
    for line in lines:
        body = line.removeprefix("data: ").strip()
        if not body or body == "[DONE]":
            continue
        event = json.loads(body)
        if event.get("type") == "tool-output-available" and event.get("preliminary"):
            continue
        events.append(_canon(event, mapping))
    return events


def _assistant(text: str, *calls: tuple[str, str, str]) -> messages_.Message:
    parts: list[messages_.Part] = [messages_.TextPart(text=text)]
    for tc_id, name, args in calls:
        parts.append(
            messages_.ToolCallPart(tool_call_id=tc_id, tool_name=name, tool_args=args)
        )
    return messages_.Message(role="assistant", parts=parts)


async def _capture_run(
    session_id: str, prompt: str, park_event: str
) -> tuple[list[str], list[dict[str, Any]]]:
    """Start a session, stream it like a POST /chat would, run until parked."""

    async def collect() -> list[str]:
        return [line async for line in chat.to_sse(session_id, 0)]

    capture = asyncio.create_task(collect())
    await start_session(session_id, prompt)
    await wait_for_lifecycle(session_id, park_event)
    sse = await asyncio.wait_for(capture, 10)

    # the history exactly as the UI receives it on reload: through the real
    # GET /sessions/{id} endpoint (which also rebuilds subagent MessageBundles
    # into the nested UIMessage shape — server-side logic this test covers).
    await sessions.create_session(session_id)
    transport = httpx.ASGITransport(app=server.app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.get(f"/api/sessions/{session_id}")
    assert response.status_code == 200
    ui_messages: list[dict[str, Any]] = response.json()["messages"]
    return sse, ui_messages


def _check_or_update(
    scenario: str, sse: list[str], ui_messages: list[dict[str, Any]]
) -> None:
    directory = FIXTURES_DIR / scenario
    if UPDATE:
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "sse.txt").write_text("".join(sse), encoding="utf-8")
        (directory / "ui_messages.json").write_text(
            json.dumps(ui_messages, indent=1) + "\n", encoding="utf-8"
        )
        return

    fixture_sse = (directory / "sse.txt").read_text(encoding="utf-8")
    fixture_lines = [f"{block}\n\n" for block in fixture_sse.split("\n\n") if block]
    assert _sse_projection(sse) == _sse_projection(fixture_lines), (
        f"{scenario}: live stream diverged from common_fixtures; "
        "regenerate with UPDATE_FIXTURES=1 if the change is intentional"
    )

    fixture_ui = json.loads(
        (directory / "ui_messages.json").read_text(encoding="utf-8")
    )
    assert _canon(ui_messages) == _canon(fixture_ui), (
        f"{scenario}: session history rendering diverged from common_fixtures"
    )


async def _submit_approval_request_fixture(
    scenario: str, session_id: str
) -> dict[str, proto.ToolApprovalResponse]:
    """Feed the client-generated approval POST back through the server path.

    Returns the approvals by tool_call_id so the caller can assert effects.
    """
    path = FIXTURES_DIR / scenario / "approval_request.json"
    if not path.exists():
        pytest.skip(
            f"{path} not generated yet — run UPDATE_FIXTURES=1 pnpm test in frontend/"
        )
    body = json.loads(path.read_text(encoding="utf-8"))

    # exactly what server.post_chat does with the request
    ui_messages = [ai_sdk.UIMessage.model_validate(m) for m in body["messages"]]
    messages, approvals = ai_sdk.to_messages(ui_messages)
    assert approvals, "client request carries no approval responses"
    assert messages[-1].role != "user", (
        "approval resubmission must not be mistaken for a new user turn"
    )

    responses = [
        proto.ToolApprovalResponse(
            tool_call_id=approval.tool_call_id,
            granted=approval.granted,
            reason=approval.reason,
        )
        for approval in approvals
    ]
    await chat.submit_approvals(session_id, responses)
    return {response.tool_call_id: response for response in responses}


async def test_parallel_approvals(
    world: InProcessWorld, scripted_model: MockProvider
) -> None:
    scripted_model.responses = [
        [
            _assistant(
                "running both",
                ("tc-a", "bash", '{"command": "echo alpha-out"}'),
                ("tc-b", "bash", '{"command": "echo beta-out"}'),
            )
        ],
        [text_msg("both handled")],
    ]

    sse, ui_messages = await _capture_run(
        "s1", "run both commands", proto.TOOL_APPROVAL_REQUESTED
    )

    _check_or_update("parallel-approvals", sse, ui_messages)

    # the client answers: grant tc-a, deny tc-b (fixture generated by frontend)
    approvals = await _submit_approval_request_fixture("parallel-approvals", "s1")
    assert approvals["tc-a"].granted and not approvals["tc-b"].granted

    await wait_for_lifecycle("s1", proto.SESSION_WAITING)
    state = await session.read_session("s1")
    assert state is not None
    assert_message_invariants(state.messages)
    results = {
        part.tool_call_id: part
        for message in state.messages
        for part in message.tool_results
    }
    assert results["tc-a"].result == "alpha-out\n"
    assert not results["tc-a"].is_error
    assert results["tc-b"].is_error
    assert "Rejected" in str(results["tc-b"].result)


async def test_parallel_subagents(
    world: InProcessWorld, scripted_model: MockProvider
) -> None:
    scripted_model.responses = [
        [
            _assistant(
                "delegating to both",
                ("tc-sa", "subagent", '{"prompt": "task-alpha", "name": "alpha"}'),
                ("tc-sb", "subagent", '{"prompt": "task-beta", "name": "beta"}'),
            )
        ],
        [text_msg("combined findings")],
    ]
    scripted_model.keyed_responses = {
        "task-alpha": [text_msg("alpha report")],
        "task-beta": [text_msg("beta report")],
    }

    sse, ui_messages = await _capture_run(
        "s1", "delegate to two helpers", proto.SESSION_WAITING
    )

    state = await session.read_session("s1")
    assert state is not None
    assert_message_invariants(state.messages)

    # each child's transcript landed on its own tool call (no cross-wiring)
    results = {
        part.tool_call_id: part
        for message in state.messages
        for part in message.tool_results
    }
    for tc_id, expected in [("tc-sa", "alpha report"), ("tc-sb", "beta report")]:
        bundle = ai.agents.MessageBundle.model_validate(results[tc_id].result)
        assert bundle.messages[-1].text == expected

    _check_or_update("parallel-subagents", sse, ui_messages)


async def test_mixed_subagents_and_approvals(
    world: InProcessWorld, scripted_model: MockProvider
) -> None:
    scripted_model.responses = [
        [
            _assistant(
                "delegating and running",
                ("tc-sub", "subagent", '{"prompt": "task-gamma", "name": "gamma"}'),
                ("tc-cmd", "bash", '{"command": "echo gamma-out"}'),
            )
        ],
        [text_msg("wrapped up")],
    ]
    scripted_model.keyed_responses = {"task-gamma": [text_msg("gamma report")]}

    sse, ui_messages = await _capture_run(
        "s1", "delegate and run", proto.TOOL_APPROVAL_REQUESTED
    )
    _check_or_update("mixed-subagents-approvals", sse, ui_messages)

    approvals = await _submit_approval_request_fixture(
        "mixed-subagents-approvals", "s1"
    )
    assert approvals["tc-cmd"].granted

    await wait_for_lifecycle("s1", proto.SESSION_WAITING)
    state = await session.read_session("s1")
    assert state is not None
    assert_message_invariants(state.messages)
    results = {
        part.tool_call_id: part
        for message in state.messages
        for part in message.tool_results
    }
    assert results["tc-cmd"].result == "gamma-out\n"
    bundle = ai.agents.MessageBundle.model_validate(results["tc-sub"].result)
    assert bundle.messages[-1].text == "gamma report"
